---
all: 
  children: 
     core_sws:
         hosts:
             s1: 
                ansible_host: 192.168.1.5
     access_sws:
         hosts:
              s2:      
                ansible_host: 192.168.1.6

