---
- name: run test
  hosts: all 
  gather_facts: no 
  connection: local  
  tasks: 
    - name: testing connection 
      cisco.ios.ios_ping: 
         dest: "{{item}}"
      with_items: 
           - 192.168.1.5
           - 192.168.1.6
           - 192.168.1.2
           - 192.168.1.11 
           - 192.168.1.3    
